version: '3.8'

services:
  website:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount the specific website project
      - ${WEBSITE_PATH:-../websites/main}:/app
      # Exclude node_modules from being overwritten
      - /app/node_modules
    restart: unless-stopped

  # Development service for hot reloading
  website-dev:
    profiles: ["dev"]
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ${WEBSITE_PATH:-../websites/main}:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped